sudo: false
dist: trusty
addons:
  apt:
    packages:
      - oracle-java8-installer

language: java

jdk:
  - oraclejdk8

install: mvn install -DskipTests=true -Popensource

script: mvn clean test -Popensource


notifications:
  email: 
    - andyglick@gmail.com
